CREATE DATABASE feeddb;
GO
USE feeddb;
GO

CREATE TABLE Feed(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Title NVARCHAR(512) NOT NULL UNIQUE,
    PublishDate DATETIME2 NOT NULL,
    ExpiryDate DATETIME2 NOT NULL
)